/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 LumberHut.vox.gltf -t --shadows -i -T 
Files: LumberHut.vox.gltf [141.94KB] > LumberHut.vox-transformed.glb [16.41KB] (88%)
*/

import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Mesh, MeshStandardMaterial, Vector3 } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Node: Mesh;
  };
  materials: {
    palette: MeshStandardMaterial;
  };
};

const position = new Vector3(-4, -4.16, 0);

function Lumberhut(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/LumberHut.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.06}>
      <mesh castShadow receiveShadow geometry={nodes.Node.geometry} material={materials.palette} position={position} />
    </group>
  );
}

export default Lumberhut;

useGLTF.preload('/glb/LumberHut.glb');
