/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 StoneQuarry.gltf -t -i -T -S --shadows 
Files: StoneQuarry.gltf [208.95KB] > StoneQuarry-transformed.glb [19.15KB] (91%)
*/

import { useGLTF } from '@react-three/drei';
import { Mesh, MeshStandardMaterial, Vector3 } from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Node: Mesh;
  };
  materials: {
    palette: MeshStandardMaterial;
  };
};

const position = new Vector3(0, -2.1, 0);

function StoneQuarry(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/StoneQuarry.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.12}>
      <mesh castShadow receiveShadow geometry={nodes.Node.geometry} material={materials.palette} position={position} />
    </group>
  );
}

useGLTF.preload('/glb/StoneQuarry.glb');

export default StoneQuarry;
