/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 CornField.vox.gltf -t --shadows --instance --transform 
Files: CornField.vox.gltf [314.42KB] > CornField.vox-transformed.glb [29.78KB] (91%)
*/

import { useGLTF } from '@react-three/drei';
import { Mesh, MeshStandardMaterial, Vector3 } from 'three';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Node: Mesh;
  };
  materials: {
    palette: MeshStandardMaterial;
  };
};

const position = new Vector3(0, -1.67, 0);

const CornField = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/glb/CornField.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.15}>
      <mesh castShadow receiveShadow geometry={nodes.Node.geometry} material={materials.palette} position={position} />
    </group>
  );
};

useGLTF.preload('/glb/CornField.glb');

export default CornField;
