/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 House-2.gltf -t -i -T --shadows 
Files: House-2.gltf [50.24KB] > House-2-transformed.glb [14.77KB] (71%)
*/

import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { Mesh, MeshStandardMaterial, Vector3 } from 'three';

type GLTFResult = GLTF & {
  nodes: {
    Model: Mesh;
  };
  materials: {
    PlainTexture: MeshStandardMaterial;
  };
};

const position = new Vector3(0, -9, 0);

function House(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/glb/House.glb') as GLTFResult;
  return (
    <group {...props} dispose={null} scale={0.01}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Model.geometry}
        material={materials.PlainTexture}
        position={position}
      />
    </group>
  );
}

export default House;

useGLTF.preload('/glb/House.glb');
